# Generated by Django 4.1.3 on 2022-11-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_ngan_hang", models.CharField(max_length=120)),
                ("lai_suat", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
