# Generated by Django 4.1.3 on 2022-11-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interestapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bank", options={"ordering": ("ten_ngan_hang", "lai_suat")},
        ),
    ]
