# Generated by Django 4.1.3 on 2022-11-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interestapp", "0002_alter_bank_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="lai_suat",
            field=models.DecimalField(
                decimal_places=2, help_text="Lãi suất mua nhà", max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="ten_ngan_hang",
            field=models.CharField(help_text="Tên ngân hàng", max_length=120),
        ),
    ]
